apiVersion: v1
kind: Service
metadata:
  name: {{ include "status-service.fullname" . }}
  labels:
    {{- include "status-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
      protocol: TCP
      name: http
    - port: {{ .Values.service.additional }}
      targetPort: 8001
      protocol: TCP
      name: metric
  selector:
    {{- include "status-service.selectorLabels" . | nindent 4 }}
